// <auto-generated />
using System;
using Infosys.CodeFirstCore.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infosys.CodeFirstCore.DataAccessLayer.Migrations
{
    [DbContext(typeof(QuickKartDbCoreContext))]
    [Migration("20260315112625_ConfigureModelBuilds")]
    partial class ConfigureModelBuilds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.CardDetail", b =>
                {
                    b.Property<decimal>("CardNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cvvnumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("NameOnCard")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardNumber");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.Category", b =>
                {
                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.HasAlternateKey("CategoryName")
                        .HasName("uq_CategoryName");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte?>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasAlternateKey("ProductName")
                        .HasName("uq_ProductName");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.PurchaseDetail", b =>
                {
                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("bigint");

                    b.Property<short>("QuantityPurchased")
                        .HasColumnType("smallint");

                    b.HasKey("EmailId");

                    b.HasIndex("ProductId");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.Role", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.User", b =>
                {
                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.Product", b =>
                {
                    b.HasOne("Infosys.CodeFirstCore.DataAccessLayer.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.PurchaseDetail", b =>
                {
                    b.HasOne("Infosys.CodeFirstCore.DataAccessLayer.Models.User", "Email")
                        .WithMany("PurchaseDetail")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infosys.CodeFirstCore.DataAccessLayer.Models.Product", "Product")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductId");

                    b.Navigation("Email");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.User", b =>
                {
                    b.HasOne("Infosys.CodeFirstCore.DataAccessLayer.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.Product", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Infosys.CodeFirstCore.DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("PurchaseDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
